// CartaOS Mock Data — Real biotech deal precedents for demo
// All financial figures are from public announcements / SEC filings

export interface MockDeal {
  id: string;
  title: string;
  dealType: string;
  announcedDate: string;
  status: string;
  licensorName: string;
  licenseeName: string;
  assetName: string;
  therapeuticArea: string;
  modality: string;
  indication: string;
  developmentStage: string;
  upfrontPayment: number | null;
  totalDealValue: number | null;
  developmentMilestones: number | null;
  commercialMilestones: number | null;
  royaltyRangeLow: number | null;
  royaltyRangeHigh: number | null;
  territoryScope: string;
  exclusivity: boolean;
  coDevRights: boolean;
  coPromoteRights: boolean;
  optionStructure: string | null;
  sourceType: string;
  confidence: number;
  verified: boolean;
}

export const MOCK_DEALS: MockDeal[] = [
  {
    id: "deal-001",
    title: "Pfizer–Seagen ADC Platform",
    dealType: "COLLABORATION",
    announcedDate: "2023-12-14",
    status: "CLOSED",
    licensorName: "Seagen",
    licenseeName: "Pfizer",
    assetName: "ADC Platform",
    therapeuticArea: "Oncology",
    modality: "Antibody-Drug Conjugate (ADC)",
    indication: "Solid Tumors",
    developmentStage: "PHASE_2",
    upfrontPayment: 700,
    totalDealValue: 4200,
    developmentMilestones: 1500,
    commercialMilestones: 2000,
    royaltyRangeLow: 12,
    royaltyRangeHigh: 20,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.95,
    verified: true,
  },
  {
    id: "deal-002",
    title: "AbbVie–ImmunoGen ADC License",
    dealType: "OUT_LICENSE",
    announcedDate: "2023-11-30",
    status: "CLOSED",
    licensorName: "ImmunoGen",
    licenseeName: "AbbVie",
    assetName: "Elahere (mirvetuximab soravtansine)",
    therapeuticArea: "Oncology",
    modality: "Antibody-Drug Conjugate (ADC)",
    indication: "Ovarian Cancer",
    developmentStage: "APPROVED",
    upfrontPayment: 250,
    totalDealValue: 2900,
    developmentMilestones: 800,
    commercialMilestones: 1850,
    royaltyRangeLow: 15,
    royaltyRangeHigh: 24,
    territoryScope: "Worldwide ex-Japan",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.92,
    verified: true,
  },
  {
    id: "deal-003",
    title: "Merck–Kelun-Biotech ADC Option",
    dealType: "OPTION",
    announcedDate: "2023-12-20",
    status: "CLOSED",
    licensorName: "Kelun-Biotech",
    licenseeName: "Merck",
    assetName: "ADC Candidates",
    therapeuticArea: "Oncology",
    modality: "Antibody-Drug Conjugate (ADC)",
    indication: "Multiple Solid Tumors",
    developmentStage: "PHASE_2",
    upfrontPayment: 175,
    totalDealValue: 9400,
    developmentMilestones: 3500,
    commercialMilestones: 5725,
    royaltyRangeLow: 8,
    royaltyRangeHigh: 16,
    territoryScope: "Worldwide ex-China",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: "Opt-in after Phase 1 data",
    sourceType: "PRESS_RELEASE",
    confidence: 0.88,
    verified: true,
  },
  {
    id: "deal-004",
    title: "BMS–SystImmune ADC Co-Dev",
    dealType: "COLLABORATION",
    announcedDate: "2024-01-08",
    status: "CLOSED",
    licensorName: "SystImmune",
    licenseeName: "Bristol-Myers Squibb",
    assetName: "BL-B01D1",
    therapeuticArea: "Oncology",
    modality: "Antibody-Drug Conjugate (ADC)",
    indication: "NSCLC, Breast Cancer",
    developmentStage: "PHASE_1",
    upfrontPayment: 800,
    totalDealValue: 8400,
    developmentMilestones: 2800,
    commercialMilestones: 4800,
    royaltyRangeLow: 10,
    royaltyRangeHigh: 18,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: true,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.94,
    verified: true,
  },
  {
    id: "deal-005",
    title: "AstraZeneca–Daiichi Sankyo T-DXd Expansion",
    dealType: "COLLABORATION",
    announcedDate: "2023-03-27",
    status: "CLOSED",
    licensorName: "Daiichi Sankyo",
    licenseeName: "AstraZeneca",
    assetName: "Enhertu (T-DXd)",
    therapeuticArea: "Oncology",
    modality: "Antibody-Drug Conjugate (ADC)",
    indication: "HER2+ Cancers",
    developmentStage: "PHASE_3",
    upfrontPayment: 1350,
    totalDealValue: 5800,
    developmentMilestones: 1800,
    commercialMilestones: 2650,
    royaltyRangeLow: 18,
    royaltyRangeHigh: 26,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: true,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.97,
    verified: true,
  },
  {
    id: "deal-006",
    title: "Novartis–BeiGene Tislelizumab",
    dealType: "COLLABORATION",
    announcedDate: "2024-01-03",
    status: "CLOSED",
    licensorName: "BeiGene",
    licenseeName: "Novartis",
    assetName: "Tislelizumab",
    therapeuticArea: "Oncology",
    modality: "Monoclonal Antibody (mAb)",
    indication: "Multiple Cancers",
    developmentStage: "PHASE_3",
    upfrontPayment: 300,
    totalDealValue: 2200,
    developmentMilestones: 700,
    commercialMilestones: 1200,
    royaltyRangeLow: 14,
    royaltyRangeHigh: 22,
    territoryScope: "North America, EU, Japan",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.91,
    verified: true,
  },
  {
    id: "deal-007",
    title: "GSK–Aiolos Bio Acquisition",
    dealType: "M_AND_A",
    announcedDate: "2023-12-18",
    status: "CLOSED",
    licensorName: "Aiolos Bio",
    licenseeName: "GSK",
    assetName: "AIO-001 (anti-TSLP mAb)",
    therapeuticArea: "Immunology",
    modality: "Monoclonal Antibody (mAb)",
    indication: "Asthma",
    developmentStage: "PHASE_1",
    upfrontPayment: 1000,
    totalDealValue: 1400,
    developmentMilestones: 400,
    commercialMilestones: null,
    royaltyRangeLow: null,
    royaltyRangeHigh: null,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "PRESS_RELEASE",
    confidence: 0.96,
    verified: true,
  },
  {
    id: "deal-008",
    title: "Sanofi–Inhibrx INBRX-101 Option",
    dealType: "OPTION",
    announcedDate: "2024-02-12",
    status: "CLOSED",
    licensorName: "Inhibrx",
    licenseeName: "Sanofi",
    assetName: "INBRX-101",
    therapeuticArea: "Rare Disease",
    modality: "Monoclonal Antibody (mAb)",
    indication: "Alpha-1 Antitrypsin Deficiency",
    developmentStage: "PHASE_2",
    upfrontPayment: 120,
    totalDealValue: 2200,
    developmentMilestones: 800,
    commercialMilestones: 1280,
    royaltyRangeLow: 10,
    royaltyRangeHigh: 18,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: "Opt-in after Phase 2 readout",
    sourceType: "SEC_FILING",
    confidence: 0.90,
    verified: true,
  },
  {
    id: "deal-009",
    title: "Gilead–CymaBay Seladelpar Acquisition",
    dealType: "M_AND_A",
    announcedDate: "2024-02-06",
    status: "CLOSED",
    licensorName: "CymaBay Therapeutics",
    licenseeName: "Gilead Sciences",
    assetName: "Seladelpar",
    therapeuticArea: "Metabolic / Endocrinology",
    modality: "Small Molecule",
    indication: "Primary Biliary Cholangitis",
    developmentStage: "PHASE_3",
    upfrontPayment: 4300,
    totalDealValue: 4300,
    developmentMilestones: null,
    commercialMilestones: null,
    royaltyRangeLow: null,
    royaltyRangeHigh: null,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.98,
    verified: true,
  },
  {
    id: "deal-010",
    title: "Takeda–Nimbus TYK2 Acquisition",
    dealType: "M_AND_A",
    announcedDate: "2023-12-04",
    status: "CLOSED",
    licensorName: "Nimbus Therapeutics",
    licenseeName: "Takeda",
    assetName: "NDI-034858 (TYK2 inhibitor)",
    therapeuticArea: "Immunology",
    modality: "Small Molecule",
    indication: "Psoriasis, Psoriatic Arthritis",
    developmentStage: "PHASE_2",
    upfrontPayment: 4000,
    totalDealValue: 6000,
    developmentMilestones: 2000,
    commercialMilestones: null,
    royaltyRangeLow: null,
    royaltyRangeHigh: null,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "PRESS_RELEASE",
    confidence: 0.95,
    verified: true,
  },
  {
    id: "deal-011",
    title: "Roche–Carmot GLP-1 Acquisition",
    dealType: "M_AND_A",
    announcedDate: "2023-12-04",
    status: "CLOSED",
    licensorName: "Carmot Therapeutics",
    licenseeName: "Roche",
    assetName: "CT-388 (GLP-1/GIP dual agonist)",
    therapeuticArea: "Metabolic / Endocrinology",
    modality: "Peptide",
    indication: "Obesity, Type 2 Diabetes",
    developmentStage: "PHASE_2",
    upfrontPayment: 2700,
    totalDealValue: 2700,
    developmentMilestones: null,
    commercialMilestones: null,
    royaltyRangeLow: null,
    royaltyRangeHigh: null,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "PRESS_RELEASE",
    confidence: 0.93,
    verified: true,
  },
  {
    id: "deal-012",
    title: "BioNTech–Biotheus mAb License",
    dealType: "OUT_LICENSE",
    announcedDate: "2024-01-22",
    status: "CLOSED",
    licensorName: "Biotheus",
    licenseeName: "BioNTech",
    assetName: "PM8002 (anti-PD-L1/VEGF)",
    therapeuticArea: "Oncology",
    modality: "Monoclonal Antibody (mAb)",
    indication: "NSCLC, Gastric Cancer",
    developmentStage: "PHASE_2",
    upfrontPayment: 155,
    totalDealValue: 1500,
    developmentMilestones: 500,
    commercialMilestones: 845,
    royaltyRangeLow: 9,
    royaltyRangeHigh: 16,
    territoryScope: "Worldwide ex-Greater China",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "PRESS_RELEASE",
    confidence: 0.87,
    verified: true,
  },
  {
    id: "deal-013",
    title: "Novo Nordisk–Inversago CB1 Blocker",
    dealType: "OPTION",
    announcedDate: "2024-03-11",
    status: "CLOSED",
    licensorName: "Inversago Pharma",
    licenseeName: "Novo Nordisk",
    assetName: "INV-202 (peripherally-restricted CB1 blocker)",
    therapeuticArea: "Metabolic / Endocrinology",
    modality: "Small Molecule",
    indication: "Obesity, NASH",
    developmentStage: "PHASE_1",
    upfrontPayment: 85,
    totalDealValue: 1650,
    developmentMilestones: 600,
    commercialMilestones: 965,
    royaltyRangeLow: 8,
    royaltyRangeHigh: 14,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: "Opt-in after Phase 1b data",
    sourceType: "PRESS_RELEASE",
    confidence: 0.85,
    verified: true,
  },
  {
    id: "deal-014",
    title: "Boehringer Ingelheim–OSE Immunotherapeutics",
    dealType: "OPTION",
    announcedDate: "2024-02-28",
    status: "CLOSED",
    licensorName: "OSE Immunotherapeutics",
    licenseeName: "Boehringer Ingelheim",
    assetName: "OSE-230 (anti-IL-7R mAb)",
    therapeuticArea: "Oncology",
    modality: "Monoclonal Antibody (mAb)",
    indication: "Immuno-Oncology",
    developmentStage: "PHASE_1",
    upfrontPayment: 28,
    totalDealValue: 1300,
    developmentMilestones: 450,
    commercialMilestones: 822,
    royaltyRangeLow: 5,
    royaltyRangeHigh: 11,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: "Opt-in after Phase 1 completion",
    sourceType: "PRESS_RELEASE",
    confidence: 0.82,
    verified: true,
  },
  {
    id: "deal-015",
    title: "J&J–Legend Biotech CARVYKTI",
    dealType: "COLLABORATION",
    announcedDate: "2023-01-15",
    status: "CLOSED",
    licensorName: "Legend Biotech",
    licenseeName: "Johnson & Johnson",
    assetName: "CARVYKTI (ciltacabtagene autoleucel)",
    therapeuticArea: "Oncology",
    modality: "Cell Therapy (CAR-T/NK)",
    indication: "Multiple Myeloma",
    developmentStage: "APPROVED",
    upfrontPayment: 350,
    totalDealValue: 3500,
    developmentMilestones: 1200,
    commercialMilestones: 1950,
    royaltyRangeLow: 16,
    royaltyRangeHigh: 22,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: true,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.93,
    verified: true,
  },
  {
    id: "deal-016",
    title: "Amgen–Horizon Therapeutics Acquisition",
    dealType: "M_AND_A",
    announcedDate: "2023-10-06",
    status: "CLOSED",
    licensorName: "Horizon Therapeutics",
    licenseeName: "Amgen",
    assetName: "TEPEZZA (teprotumumab)",
    therapeuticArea: "Rare Disease",
    modality: "Monoclonal Antibody (mAb)",
    indication: "Thyroid Eye Disease",
    developmentStage: "APPROVED",
    upfrontPayment: 27800,
    totalDealValue: 27800,
    developmentMilestones: null,
    commercialMilestones: null,
    royaltyRangeLow: null,
    royaltyRangeHigh: null,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.99,
    verified: true,
  },
  {
    id: "deal-017",
    title: "AZ–Fusion Pharma Radiopharmaceuticals",
    dealType: "M_AND_A",
    announcedDate: "2023-12-19",
    status: "CLOSED",
    licensorName: "Fusion Pharmaceuticals",
    licenseeName: "AstraZeneca",
    assetName: "FPI-2265 (225Ac-PSMA)",
    therapeuticArea: "Oncology",
    modality: "Radiopharmaceutical",
    indication: "Prostate Cancer",
    developmentStage: "PHASE_2",
    upfrontPayment: 2000,
    totalDealValue: 2400,
    developmentMilestones: 400,
    commercialMilestones: null,
    royaltyRangeLow: null,
    royaltyRangeHigh: null,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: false,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "PRESS_RELEASE",
    confidence: 0.94,
    verified: true,
  },
  {
    id: "deal-018",
    title: "Pfizer–Arvinas PROTAC Collaboration",
    dealType: "COLLABORATION",
    announcedDate: "2023-07-19",
    status: "CLOSED",
    licensorName: "Arvinas",
    licenseeName: "Pfizer",
    assetName: "ARV-766 (AR PROTAC degrader)",
    therapeuticArea: "Oncology",
    modality: "Small Molecule",
    indication: "mCRPC (Prostate Cancer)",
    developmentStage: "PHASE_2",
    upfrontPayment: 650,
    totalDealValue: 1000,
    developmentMilestones: 250,
    commercialMilestones: 100,
    royaltyRangeLow: 10,
    royaltyRangeHigh: 15,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: true,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.91,
    verified: true,
  },
  {
    id: "deal-019",
    title: "Lilly–DICE GLP-1 Oral",
    dealType: "COLLABORATION",
    announcedDate: "2024-03-05",
    status: "ANNOUNCED",
    licensorName: "DICE Therapeutics",
    licenseeName: "Eli Lilly",
    assetName: "Oral GLP-1 agonist",
    therapeuticArea: "Metabolic / Endocrinology",
    modality: "Small Molecule",
    indication: "Obesity, Type 2 Diabetes",
    developmentStage: "PHASE_1",
    upfrontPayment: 500,
    totalDealValue: 3200,
    developmentMilestones: 1100,
    commercialMilestones: 1600,
    royaltyRangeLow: 10,
    royaltyRangeHigh: 16,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "PRESS_RELEASE",
    confidence: 0.86,
    verified: false,
  },
  {
    id: "deal-020",
    title: "Roche–Alnylam RNAi Collaboration",
    dealType: "COLLABORATION",
    announcedDate: "2023-11-14",
    status: "CLOSED",
    licensorName: "Alnylam Pharmaceuticals",
    licenseeName: "Roche",
    assetName: "siRNA Candidates (Alzheimer's, Neuro)",
    therapeuticArea: "Neurology",
    modality: "siRNA / ASO",
    indication: "Alzheimer's Disease",
    developmentStage: "PRECLINICAL",
    upfrontPayment: 310,
    totalDealValue: 3900,
    developmentMilestones: 1400,
    commercialMilestones: 2190,
    royaltyRangeLow: 12,
    royaltyRangeHigh: 20,
    territoryScope: "Worldwide",
    exclusivity: true,
    coDevRights: true,
    coPromoteRights: false,
    optionStructure: null,
    sourceType: "SEC_FILING",
    confidence: 0.90,
    verified: true,
  },
];

export interface MockCompany {
  id: string;
  name: string;
  type: string;
  headquarters: string;
  website: string;
  marketCap: number | null;
  therapeuticFocus: string[];
  modalityFocus: string[];
  avgDealCadenceDays: number | null;
  dealActivityScore: number;
  partnerStatus: string;
  partnerScore: number;
  lastDealDate: string | null;
  notes: string;
  contactName: string;
  contactTitle: string;
  contactEmail: string;
}

export const MOCK_COMPANIES: MockCompany[] = [
  {
    id: "co-001",
    name: "Pfizer",
    type: "PHARMA",
    headquarters: "New York, NY",
    website: "pfizer.com",
    marketCap: 160000,
    therapeuticFocus: ["Oncology", "Immunology", "Rare Disease"],
    modalityFocus: ["Small Molecule", "Antibody-Drug Conjugate (ADC)", "mRNA"],
    avgDealCadenceDays: 45,
    dealActivityScore: 92,
    partnerStatus: "IN_DISCUSSION",
    partnerScore: 88,
    lastDealDate: "2024-01-15",
    notes: "Active interest in ADC and PROTAC platforms. BD lead responsive.",
    contactName: "Sarah Chen",
    contactTitle: "VP, Business Development",
    contactEmail: "s.chen@pfizer.com",
  },
  {
    id: "co-002",
    name: "AstraZeneca",
    type: "PHARMA",
    headquarters: "Cambridge, UK",
    website: "astrazeneca.com",
    marketCap: 220000,
    therapeuticFocus: ["Oncology", "Cardiovascular", "Respiratory"],
    modalityFocus: ["Antibody-Drug Conjugate (ADC)", "Monoclonal Antibody (mAb)", "Bispecific Antibody"],
    avgDealCadenceDays: 60,
    dealActivityScore: 95,
    partnerStatus: "CONTACTED",
    partnerScore: 91,
    lastDealDate: "2024-02-20",
    notes: "Strong ADC franchise. Looking to expand beyond HER2.",
    contactName: "James Wright",
    contactTitle: "Head of Oncology Partnerships",
    contactEmail: "j.wright@astrazeneca.com",
  },
  {
    id: "co-003",
    name: "Novartis",
    type: "PHARMA",
    headquarters: "Basel, Switzerland",
    website: "novartis.com",
    marketCap: 200000,
    therapeuticFocus: ["Oncology", "Immunology", "Neurology", "Cardiovascular"],
    modalityFocus: ["Small Molecule", "Monoclonal Antibody (mAb)", "Cell Therapy (CAR-T/NK)", "Gene Therapy"],
    avgDealCadenceDays: 55,
    dealActivityScore: 88,
    partnerStatus: "IDENTIFIED",
    partnerScore: 85,
    lastDealDate: "2024-01-03",
    notes: "Broad therapeutic interest. Strong in IO and cell therapy.",
    contactName: "Maria Hoffmann",
    contactTitle: "Global Head, BD&L",
    contactEmail: "m.hoffmann@novartis.com",
  },
  {
    id: "co-004",
    name: "Roche",
    type: "PHARMA",
    headquarters: "Basel, Switzerland",
    website: "roche.com",
    marketCap: 230000,
    therapeuticFocus: ["Oncology", "Neurology", "Immunology"],
    modalityFocus: ["Monoclonal Antibody (mAb)", "Bispecific Antibody", "siRNA / ASO", "Small Molecule"],
    avgDealCadenceDays: 50,
    dealActivityScore: 90,
    partnerStatus: "ACTIVE",
    partnerScore: 93,
    lastDealDate: "2024-03-01",
    notes: "Active co-development partner. Strong regulatory team.",
    contactName: "Thomas Müller",
    contactTitle: "SVP, Strategic Alliances",
    contactEmail: "t.mueller@roche.com",
  },
  {
    id: "co-005",
    name: "Merck & Co.",
    type: "PHARMA",
    headquarters: "Rahway, NJ",
    website: "merck.com",
    marketCap: 310000,
    therapeuticFocus: ["Oncology", "Infectious Disease", "Cardiovascular"],
    modalityFocus: ["Small Molecule", "Antibody-Drug Conjugate (ADC)", "Monoclonal Antibody (mAb)"],
    avgDealCadenceDays: 40,
    dealActivityScore: 94,
    partnerStatus: "IN_DISCUSSION",
    partnerScore: 90,
    lastDealDate: "2024-02-15",
    notes: "Aggressively building ADC pipeline post-Kelun deal.",
    contactName: "Michael Park",
    contactTitle: "VP, Oncology BD",
    contactEmail: "m.park@merck.com",
  },
  {
    id: "co-006",
    name: "Bristol-Myers Squibb",
    type: "PHARMA",
    headquarters: "Princeton, NJ",
    website: "bms.com",
    marketCap: 100000,
    therapeuticFocus: ["Oncology", "Hematology", "Immunology", "Cardiovascular"],
    modalityFocus: ["Antibody-Drug Conjugate (ADC)", "Cell Therapy (CAR-T/NK)", "Small Molecule"],
    avgDealCadenceDays: 50,
    dealActivityScore: 86,
    partnerStatus: "CONTACTED",
    partnerScore: 82,
    lastDealDate: "2024-01-08",
    notes: "Large IO franchise, looking for next-gen approaches.",
    contactName: "Lisa Johnson",
    contactTitle: "Director, Business Development",
    contactEmail: "l.johnson@bms.com",
  },
  {
    id: "co-007",
    name: "Eli Lilly",
    type: "PHARMA",
    headquarters: "Indianapolis, IN",
    website: "lilly.com",
    marketCap: 740000,
    therapeuticFocus: ["Metabolic / Endocrinology", "Oncology", "Neurology"],
    modalityFocus: ["Peptide", "Small Molecule", "Monoclonal Antibody (mAb)"],
    avgDealCadenceDays: 35,
    dealActivityScore: 97,
    partnerStatus: "IDENTIFIED",
    partnerScore: 86,
    lastDealDate: "2024-03-05",
    notes: "Dominant in GLP-1/obesity. Expanding oncology via M&A.",
    contactName: "Robert Kim",
    contactTitle: "Head of External Innovation",
    contactEmail: "r.kim@lilly.com",
  },
  {
    id: "co-008",
    name: "Sanofi",
    type: "PHARMA",
    headquarters: "Paris, France",
    website: "sanofi.com",
    marketCap: 130000,
    therapeuticFocus: ["Immunology", "Rare Disease", "Oncology"],
    modalityFocus: ["Monoclonal Antibody (mAb)", "Small Molecule", "Gene Therapy"],
    avgDealCadenceDays: 55,
    dealActivityScore: 80,
    partnerStatus: "DECLINED",
    partnerScore: 65,
    lastDealDate: "2024-02-12",
    notes: "Dupixent franchise focus. Selective on new partnerships.",
    contactName: "Claire Dupont",
    contactTitle: "BD Director, Rare Disease",
    contactEmail: "c.dupont@sanofi.com",
  },
];

export interface MockNegotiation {
  id: string;
  title: string;
  companyId: string;
  companyName: string;
  status: string;
  proposedUpfront: number | null;
  proposedMilestones: number | null;
  proposedRoyaltyLow: number | null;
  proposedRoyaltyHigh: number | null;
  proposedTerritory: string;
  startDate: string;
  targetCloseDate: string | null;
  healthScore: number;
  blockers: { item: string; severity: string; owner: string }[];
  nextSteps: { action: string; owner: string; due: string }[];
  riskFlags: string[];
}

export const MOCK_NEGOTIATIONS: MockNegotiation[] = [
  {
    id: "neg-001",
    title: "CRX-100 Out-License — Pfizer",
    companyId: "co-001",
    companyName: "Pfizer",
    status: "TERM_SHEET_EXCHANGED",
    proposedUpfront: 250,
    proposedMilestones: 1800,
    proposedRoyaltyLow: 10,
    proposedRoyaltyHigh: 16,
    proposedTerritory: "Worldwide",
    startDate: "2024-01-15",
    targetCloseDate: "2024-06-30",
    healthScore: 72,
    blockers: [
      { item: "Legal review pending on sublicensing clause", severity: "MEDIUM", owner: "IP Counsel" },
      { item: "CMC data package incomplete", severity: "HIGH", owner: "CMC Lead" },
    ],
    nextSteps: [
      { action: "Schedule partner call to discuss IP allocation", owner: "BD Lead", due: "2024-03-15" },
      { action: "Finalize CMC data package", owner: "CMC Lead", due: "2024-03-20" },
      { action: "Draft counter-proposal on royalty step-downs", owner: "BD Lead", due: "2024-03-18" },
    ],
    riskFlags: [
      "Upfront payment offer 35% below median for comparable Phase 2 oncology deals",
      "Pfizer requesting broader sublicensing rights than industry standard",
    ],
  },
  {
    id: "neg-002",
    title: "CRX-200 ADC Platform — AstraZeneca",
    companyId: "co-002",
    companyName: "AstraZeneca",
    status: "TERM_SHEET_DRAFTING",
    proposedUpfront: null,
    proposedMilestones: null,
    proposedRoyaltyLow: null,
    proposedRoyaltyHigh: null,
    proposedTerritory: "Worldwide ex-China",
    startDate: "2024-02-28",
    targetCloseDate: "2024-09-30",
    healthScore: 58,
    blockers: [
      { item: "Waiting for AZ scientific review feedback", severity: "HIGH", owner: "AstraZeneca" },
    ],
    nextSteps: [
      { action: "Prepare benchmarking analysis for AZ meeting", owner: "BD Lead", due: "2024-03-22" },
      { action: "Draft initial term sheet with benchmarked ranges", owner: "BD Lead", due: "2024-03-25" },
    ],
    riskFlags: [
      "AZ has strong internal ADC capability — potential competitive conflict",
    ],
  },
  {
    id: "neg-003",
    title: "CRX-100 Backup Option — Merck",
    companyId: "co-005",
    companyName: "Merck & Co.",
    status: "INITIATED",
    proposedUpfront: null,
    proposedMilestones: null,
    proposedRoyaltyLow: null,
    proposedRoyaltyHigh: null,
    proposedTerritory: "Worldwide",
    startDate: "2024-03-01",
    targetCloseDate: null,
    healthScore: 45,
    blockers: [],
    nextSteps: [
      { action: "Send introductory materials and NDA", owner: "BD Lead", due: "2024-03-12" },
      { action: "Schedule introductory call", owner: "BD Lead", due: "2024-03-14" },
    ],
    riskFlags: [],
  },
];

export interface MockClause {
  id: string;
  clauseType: string;
  title: string;
  clauseText: string;
  summary: string;
  favorability: string;
  negotiationNotes: string;
  dealTitle: string;
}

export const MOCK_CLAUSES: MockClause[] = [
  {
    id: "cl-001",
    clauseType: "TERMINATION",
    title: "Termination for Convenience",
    clauseText: "Either party may terminate this Agreement upon [180] days' prior written notice to the other party, provided that such termination shall not become effective until all ongoing clinical trials have been completed or wound down in accordance with applicable regulatory requirements.",
    summary: "Standard termination for convenience with 180-day notice period and clinical trial protection.",
    favorability: "BALANCED",
    negotiationNotes: "Licensee typically pushes for shorter notice period (90 days). Licensor should insist on trial completion language.",
    dealTitle: "Pfizer–Seagen ADC Platform",
  },
  {
    id: "cl-002",
    clauseType: "IP_OWNERSHIP",
    title: "Foreground IP Allocation",
    clauseText: "All inventions, discoveries, and improvements made solely by Licensee's personnel shall be owned by Licensee. All inventions made solely by Licensor's personnel shall be owned by Licensor. Joint inventions shall be jointly owned, with each party having the right to exploit without accounting to the other.",
    summary: "Inventorship-based IP allocation with joint ownership provisions. Industry standard approach.",
    favorability: "BALANCED",
    negotiationNotes: "Key negotiation point: joint IP exploitation rights. Licensee may request exclusive license to joint IP in territory.",
    dealTitle: "AstraZeneca–Daiichi Sankyo T-DXd",
  },
  {
    id: "cl-003",
    clauseType: "ANTI_SHELVING",
    title: "Anti-Shelving / Diligence Obligation",
    clauseText: "Licensee shall use Commercially Reasonable Efforts to develop and commercialize at least one Licensed Product in the Territory. 'Commercially Reasonable Efforts' means efforts consistent with those used by a similarly situated pharmaceutical company for a product of similar market potential, taking into account safety, efficacy, competitive landscape, and regulatory requirements.",
    summary: "Anti-shelving provision requiring commercially reasonable efforts with defined standard.",
    favorability: "LICENSOR_FAVORABLE",
    negotiationNotes: "Licensees often push for narrower definition. Key: tie CRE to similarly situated company, not licensee's own portfolio prioritization.",
    dealTitle: "BMS–SystImmune ADC Co-Dev",
  },
  {
    id: "cl-004",
    clauseType: "SUBLICENSING",
    title: "Sublicensing Rights",
    clauseText: "Licensee may grant sublicenses under this Agreement only with the prior written consent of Licensor, such consent not to be unreasonably withheld. Any sublicense shall be consistent with the terms of this Agreement, and Licensee shall remain responsible for the performance of its sublicensees.",
    summary: "Sublicensing requires prior consent with reasonableness standard.",
    favorability: "LICENSOR_FAVORABLE",
    negotiationNotes: "Licensees prefer broad sublicensing rights (especially for affiliates). Compromise: allow affiliate sublicensing freely, require consent for third parties.",
    dealTitle: "Merck–Kelun ADC Option",
  },
  {
    id: "cl-005",
    clauseType: "CHANGE_OF_CONTROL",
    title: "Change of Control",
    clauseText: "In the event of a Change of Control of Licensee, Licensor shall have the right to terminate this Agreement upon [90] days' notice if the acquiring entity is a Competitor of Licensor. 'Change of Control' means any transaction resulting in a change of more than 50% of the voting securities.",
    summary: "Change of control termination right triggered by competitor acquisition.",
    favorability: "LICENSOR_FAVORABLE",
    negotiationNotes: "Licensees resist CoC termination rights. Possible compromises: convert to additional milestones, require competitor definition, or limit to specific deal terms.",
    dealTitle: "Sanofi–Inhibrx Option",
  },
  {
    id: "cl-006",
    clauseType: "MILESTONE_DEF",
    title: "Clinical Milestone Achievement",
    clauseText: "The following development milestones shall be payable upon first achievement: (a) IND filing acceptance: $[X]M; (b) First patient dosed in Phase 1: $[X]M; (c) First patient dosed in Phase 2: $[X]M; (d) Phase 2 primary endpoint met: $[X]M; (e) First patient dosed in pivotal trial: $[X]M; (f) BLA/NDA filing acceptance: $[X]M; (g) First regulatory approval (US or EU): $[X]M.",
    summary: "Standard clinical development milestone structure with 7 trigger events.",
    favorability: "BALANCED",
    negotiationNotes: "Key negotiation: milestone definition clarity (what constitutes 'primary endpoint met'?). Licensors should push for lower thresholds and more milestones.",
    dealTitle: "AbbVie–ImmunoGen ADC License",
  },
  {
    id: "cl-007",
    clauseType: "ROYALTY_STEP_DOWN",
    title: "Royalty Step-Down Provisions",
    clauseText: "Royalties shall be reduced by: (a) [50]% upon expiration of the last valid claim of the Licensed Patents covering the Licensed Product in a given country; (b) [25]% if a Generic Product has achieved [20]% or greater market share in such country; provided that the aggregate reduction shall not exceed [60]%.",
    summary: "Royalty step-downs tied to patent expiry and generic competition with floor provision.",
    favorability: "LICENSEE_FAVORABLE",
    negotiationNotes: "Licensors should negotiate for higher floors (max 40% reduction) and stricter generic market share thresholds.",
    dealTitle: "Novartis–BeiGene Tislelizumab",
  },
  {
    id: "cl-008",
    clauseType: "DISPUTE_RESOLUTION",
    title: "Dispute Resolution Mechanism",
    clauseText: "Any dispute arising out of this Agreement shall first be referred to the senior executives of each party for resolution within [30] days. If unresolved, the dispute shall be submitted to binding arbitration under the rules of the ICC in [New York/London/Geneva], conducted by three arbitrators.",
    summary: "Tiered dispute resolution: executive escalation then ICC arbitration.",
    favorability: "BALANCED",
    negotiationNotes: "Venue selection is often contested. US biotechs prefer New York; European pharma prefers London or Geneva. Three arbitrators is standard for deals >$100M.",
    dealTitle: "GSK–Aiolos Bio Acquisition",
  },
];

// Helper functions for mock data analytics
export function getDealsByTherapeuticArea() {
  const grouped: Record<string, number> = {};
  MOCK_DEALS.forEach((d) => {
    grouped[d.therapeuticArea] = (grouped[d.therapeuticArea] || 0) + 1;
  });
  return Object.entries(grouped)
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

export function getDealsByStage() {
  const grouped: Record<string, number> = {};
  MOCK_DEALS.forEach((d) => {
    grouped[d.developmentStage] = (grouped[d.developmentStage] || 0) + 1;
  });
  return Object.entries(grouped).map(([stage, count]) => ({ stage, count }));
}

export function getDealsByType() {
  const grouped: Record<string, number> = {};
  MOCK_DEALS.forEach((d) => {
    grouped[d.dealType] = (grouped[d.dealType] || 0) + 1;
  });
  return Object.entries(grouped).map(([type, count]) => ({ type, count }));
}

export function getDealsByModality() {
  const grouped: Record<string, number> = {};
  MOCK_DEALS.forEach((d) => {
    grouped[d.modality] = (grouped[d.modality] || 0) + 1;
  });
  return Object.entries(grouped)
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

export function getUpfrontStats() {
  const upfronts = MOCK_DEALS.filter((d) => d.upfrontPayment != null).map(
    (d) => d.upfrontPayment!
  );
  upfronts.sort((a, b) => a - b);
  const median = upfronts[Math.floor(upfronts.length / 2)];
  const mean = upfronts.reduce((a, b) => a + b, 0) / upfronts.length;
  const min = upfronts[0];
  const max = upfronts[upfronts.length - 1];
  return { median, mean, min, max, count: upfronts.length };
}

export function getRoyaltyStats() {
  const lows = MOCK_DEALS.filter((d) => d.royaltyRangeLow != null).map(
    (d) => d.royaltyRangeLow!
  );
  const highs = MOCK_DEALS.filter((d) => d.royaltyRangeHigh != null).map(
    (d) => d.royaltyRangeHigh!
  );
  return {
    medianLow: lows.sort((a, b) => a - b)[Math.floor(lows.length / 2)] || 0,
    medianHigh: highs.sort((a, b) => a - b)[Math.floor(highs.length / 2)] || 0,
    rangeLow: Math.min(...lows),
    rangeHigh: Math.max(...highs),
    count: lows.length,
  };
}
